version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=usersAndOrders
      - PGDATA=/var/lib/postgresql/data
    restart: always
    container_name: db
    networks:
      - my_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/usersAndOrders
      - spring.datasource.username=postgres
      - spring.datasource.password=password
      - spring.datasource.driver-class-name=org.postgresql.Driver
    ports:
      - "127.0.0.1:8080:8080"
    container_name: app
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge